experiment:
    id: all_objects_gen_filtered_1_eval_TEST

##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/all_objects_filtered_from_nuscenes/all_objects_filtered_from_nuscenes_train_val.json'
    resolution: 0.05
    dataloader: 'nuscenes'
    coordinates: 'cylindrical'
    points_per_object: -1
    align_objects: False

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 2
    num_workers: 8
    max_epoch: 100
    lr: 0.0001
    batch_size: 128
    decay_lr: 1.0e-4
    class_conditional: True

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 5.0
    visualize: False
    num_val_samples: 10

##Network
model:
    out_dim: 96
    num_conditions: 8
    cyclic_conditions: 2
    relative_angles: True