experiment:
    id: nuscenes_cars_generation_cyclical_coordinates_1

##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/cars_from_nuscenes/cars_from_nuscenes_train_val.json'
    resolution: 0.05
    dataloader: 'nuscenes'

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 4
    max_epoch: 100
    lr: 0.0001
    batch_size: 128
    decay_lr: 1.0e-4

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 5.0
    visualize: False
    num_val_samples: 10

##Network
model:
    out_dim: 96
